BUSINESS_DAYS_COUNT = 1
PERIOD_DAILY = 'daily'
DISPLAY_DATE_TIME_FORMAT_LONG = '%A, %d %B %Y %H:%M'
DISPLAY_DATE_TIME_FORMAT_SHORT = '%d %b %Y %H:%M'

INDICATOR_ROLLING_QUARTER = 'ROLQ'
INDICATOR_MOVING_ANNUAL_TOTAL = 'MAT'
INDICATOR_ROLLING_QUARTER_CHANGE_PREVIOUS_YEAR = 'rolling_quarter_change_previous_year'
INDICATOR_MOVING_ANNUAL_TOTAL_CHANGE_PREVIOUS_YEAR = 'mat_growth_change_previous_year'



INDICATOR_NEXT_CALL = 'next_call_date'
INDICATOR_CALL = 'call_date'

FRANCHISE_VACC = 'CH_VACC_A_001'

FINDING_TYPE_TRENDS = 'trends'
